name: main CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build layer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - run: npm run build

      - run: npm run deploy prod
